sudo: false
language: haskell
addons:
  apt:
    sources: [hvr-ghc]
    packages: [ghc-8.0.1, libgmp10, upx-ucl]
cache:
  directories:
  - $HOME/.stack
install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- stack --no-terminal setup
- stack --no-terminal install --only-dependencies
script:
- stack --no-terminal build
- stack exec -- nicovideo-translator --help
deploy:
- provider: hackage
  username: hongminhee
  password:
    secure: "u5yqHxvOCkzWZ3CrcZwYFBFtFvgGX9LdWfa35Pve8upsxxE1QfqnAA2lsdIK/VP+FaPlUzfwJC7AB5TZ8P/0NGZ+TfNPsjnAF7Tz5uA89Kjfu1EsaSe3YU2YBq9D6cJf/rJSDtU7gpHvFVCVvT/ElE7BUfYiuSWUNm2W3fR0I+0="
  on:
    tags: true
